# Uncomment this line to define a global platform for your project
platform :ios, "6.0"
workspace "../NBNPhotoChooser"

target "CameraPreview" do
  pod "NBNPhotoChooser", :path => "../"
end

target "CameraPreviewTests" do

end

